spring.application.name: byte-unbound

client:
  telegram:
    token: ${TELEGRAM.TOKEN}
    bot-id: ${TELEGRAM.BOT-ID}
    group-id: ${TELEGRAM.GROUP-ID}

email:
  host: imap.gmx.com
  username: ${EMAIL-USERNAME}
  password: ${EMAIL-PASSWORD}
  port: 993
  ssl: true

newsletter:
  medium:
    sender: noreply@medium.com
    article-pattern: "https://medium\\.com/@[^/]+/[^?]+\\?source=email.*"
    substring-before: "?source"
    redirect-to-host: https://freedium.cfd

spring:
  datasource:
    url: jdbc:h2:file:${DATABASE.PATH}
    username: h2
    password: password
  jpa:
    hibernate:
      ddl-auto: update
